JENKINS_TESTTYPES:
  - bareos-client-only
  - bareos-postgresql
  - univention-bareos
  - bareos-universal-client

OS:
  Fedora:
    "36":
      TYPE: rpm
      IMAGE: fedora36
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos

  EL:
    "9":
      TYPE: rpm
      IMAGE: centos9
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos
